site_name: My Docs
theme:
  name: material
  font:
    text: Noto Sans Korean
    code: Source Code Pro
  palette:
    primary: black
  features:
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.highlight
    - header.autohide
  plugins:
    - search
extra:
  generator: false
markdown_extensions:
  - pymdownx.mark
  - pymdownx.tilde
